IMAGE_SIZE: [640,640]
TRAIN_DATA_SIZE: 0.8
VAL_DATA_SIZE: 0.2

BASE_MODEL:
  MODEL_NAME: yolov8l.pt

TRAIN_MODEL_PARAMS:
  EPOCHS: 10
  BATCH_SIZE: 8
  IMAGE_SIZE: 640
  OPTIMIZER: Adam

MODEL_EVALUATE_PARAMS:
  BATCH_SIZE: 8
  IMAGE_SIZE: 640
  CONFIDENCE: 0.5