
artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/g0urav-hustler/External-Data/raw/main/PCBData.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_processing:
  source_dir: artifacts/data_ingestion/PCBData
  raw_data_dir: artifacts/data_processing/raw_data
  processed_data_dir: artifacts/data_processing/processed_data
  split_data_dir: artifacts/data_processing/split_data

base_model:
  base_model_dir = artifacts/base_models
